
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.SimpleDateFormat;
import java.util.*;


/**
 *
 * @author adria
 */
public class Usuarios extends javax.swing.JFrame implements Runnable{
String hora,minutos,segundos;
Thread hilo;    
    
   Connection con = null;
   Statement stmt = null;        
            
    public Usuarios() {
        initComponents();
        this.setTitle("APP ESDE");
        this.setLocation(400, 220);
        
        txt_Fecha.setText(fechaActual());
        hilo = new Thread(this);
        hilo.start();
        setVisible(true);
    }

    public void hora(){
        Calendar calendario = new GregorianCalendar();
        Date horaactual =new Date();
        calendario.setTime(horaactual);
        hora = calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY): "0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE): "0"+calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND): "0"+calendario.get(Calendar.SECOND);
        
    } 
    
    public void run(){
        //WHILE
        Thread current = Thread.currentThread();
//        
//        while(current==hilo){
//            hora();
//            txt_Hora.setText(hora+":"+minutos+":"+segundos);
//            
//        }
        //FOR
        for (int i = 1; i > 0; i++){
            if (i>0){
                hora();
                txt_Hora.setText(hora+":"+minutos+":"+segundos);
            }
            
        } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txt_Telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmb_TipoUsuario = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        cmb_Area = new javax.swing.JComboBox<String>();
        btn_Aceptar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        btn_Consultar = new javax.swing.JButton();
        txt_Fecha = new javax.swing.JTextField();
        txt_Hora = new javax.swing.JTextField();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreKeyTyped(evt);
            }
        });
        getContentPane().add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 180, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario Dominio:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txt_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 140, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        getContentPane().add(txt_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 160, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        txt_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 140, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        cmb_TipoUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Invitado", "Colaborador", "Administrador ", " " }));
        getContentPane().add(cmb_TipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 120, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Area:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        cmb_Area.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tecnologia", "Auditoria", "Comercial" }));
        getContentPane().add(cmb_Area, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 120, -1));

        btn_Aceptar.setText("ACEPTAR");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 263, 100, 50));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txt_ID.setEditable(false);
        txt_ID.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 30, -1));

        btn_Consultar.setText("CONSULTA");
        btn_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 110, 50));

        txt_Fecha.setEditable(false);
        txt_Fecha.setText("DD/MM/YYYY");
        getContentPane().add(txt_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 80, -1));

        txt_Hora.setEditable(false);
        txt_Hora.setText("00:00:00");
        getContentPane().add(txt_Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 70, -1));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo 4.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String fechaActual(){
        
        Date fecha= new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        
        return formatoFecha.format(fecha);
        
    }
        
    
    
    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        
        String cadena2,cadena3,cadena4,cadena5,cadena6,cadena7;
       
        cadena2 = txt_Nombre.getText();
        cadena3 = txt_Usuario.getText();
        cadena4 = txt_Pass.getText().toString();
        cadena5 = txt_Telefono.getText();
        cadena6 = cmb_TipoUsuario.getSelectedItem().toString();
        cadena7 = cmb_Area.getSelectedItem().toString();
       
     if (txt_Nombre.getText().equals("") || (txt_Usuario.getText().equals("")) || (txt_Pass.getText().equals("")) || (txt_Telefono.getText().equals(""))
          || (cmb_TipoUsuario.getSelectedItem().equals("")) || (cmb_Area.getSelectedItem().equals("")))  { 
       javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO",javax.swing.JOptionPane.INFORMATION_MESSAGE); 
        txt_Nombre.requestFocus();
    
    }
     
    else {
      try {
            String url = "jdbc:mysql://localhost:3306/appesde";
            String usuario = "root";
            String contraseña = "321904";
             Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             con =  DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
  
                  stmt = con.createStatement(); 
                  stmt.executeUpdate("INSERT INTO usuarios VALUES('" + 0 + "','"+cadena2+"','"+cadena3+"','"+cadena4+"','"+cadena5+"','"+cadena6+"','"+cadena7+"')");
                  System.out.println("Los valores han sido agregados a la base de datos ");
       } catch (InstantiationException ex) {
           Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {
           Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( Exception e ) { 
                         System.out.println( e.getMessage());
                }
            }
        }
         javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        this.txt_Nombre.setText("");
        this.txt_Usuario.setText("");
        this.txt_Pass.setText("");
        this.txt_Telefono.setText("");
          
     
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void txt_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreKeyTyped
       
        char c = evt.getKeyChar();
        if((c<'a' || c>'z')  && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
        
    }//GEN-LAST:event_txt_NombreKeyTyped

    private void txt_TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TelefonoKeyTyped
        
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
        
    }//GEN-LAST:event_txt_TelefonoKeyTyped

    private void txt_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsuarioActionPerformed

    private void btn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarActionPerformed
       
        this.dispose();
        ConsultaUsuarios cu = new ConsultaUsuarios();
        cu.setVisible(true);

    }//GEN-LAST:event_btn_ConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Consultar;
    private javax.swing.JComboBox<String> cmb_Area;
    private javax.swing.JComboBox<String> cmb_TipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JTextField txt_Fecha;
    private javax.swing.JTextField txt_Hora;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JPasswordField txt_Pass;
    private javax.swing.JTextField txt_Telefono;
    private javax.swing.JTextField txt_Usuario;
    // End of variables declaration//GEN-END:variables
}
